name: Build and test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          rustflags: ""
      - name: Check if formatted correctly
        run: |
          cargo fmt --check
      - name: Check if code builds correctly
        run: |
          cargo check
      - name: Run tests
        run: |
          cargo test
      - name: Static code analysis with clippy
        run: |
          cargo clippy --all -- -D warnings

  tests-emacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 29.4
      - name: Run ERT tests
        working-directory: emacs
        run: |
          emacs -q -batch -l ert -l deps.el -l sepl-mode.el -l tests.el -f ert-run-tests-batch-and-exit
